"use client";

import { createContext, useContext, useReducer, useEffect } from "react";

const ProductContext = createContext();

const initialState = {
  products: [
    {
      id: 1,
      name: "Beras Sania Per 1kg",
      price: 17000,
      originalPrice: 19000,
      category: "bahan-makanan",
      stock: 100,
      image: "public/foto bahan makanan/beras sania.png",
      description: "Beras berkualitas tinggi, pulen dan harum, cocok untuk konsumsi harian keluarga.",
      size: "1 kg",
      isPromo: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 2,
      name: "Bihun Jagung",
      price: 8000,
      category: "bahan-makanan",
      stock: 76,
      image: "public/foto bahan makanan/bihun jagung.png",
      description: "Bihun lembut berbahan dasar jagung, ideal untuk berbagai masakan seperti soto, sup, dan tumisan.",
      size: "300 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 3,
      name: "Minyak Fortune",
      price: 10000,
      category: "bahan-makanan",
      stock: 54,
      image: "public/foto bahan makanan/minyak fortune.png",
      description: "Minyak goreng jernih dan sehat, cocok untuk menggoreng dan menumis makanan favorit Anda.",
      size: "1/2 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 4,
      name: "Gandum Segitiga Biru",
      price: 10000,
      category: "bahan-makanan",
      stock: 95,
      image: "public/foto bahan makanan/segitiga biru.png",
      description: "Tepung terigu serbaguna dari gandum pilihan, pas untuk kue, roti, hingga gorengan.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 5,
      name: "Minyak Cup Rosebrand",
      price: 5000,
      category: "bahan-makanan",
      stock: 70,
      image: "public/foto bahan makanan/rose brand minyak cup.png",
      description: "Minyak goreng kemasan praktis, jernih dan berkualitas, dari merek terpercaya Rosebrand.",
      size: "220 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 6,
      name: "Minyak Kita",
      price: 18000,
      category: "bahan-makanan",
      stock: 85,
      image: "public/foto bahan makanan/minyak_kita-removebg-preview.png",
      description: "Minyak goreng ekonomis bersertifikat, jernih dan aman untuk konsumsi keluarga.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 7,
      name: "Margarine Royal Palmia",
      price: 9000,
      category: "bahan-makanan",
      stock: 30,
      image: "public/foto bahan makanan/palmia.png",
      description: "Margarin premium yang kaya rasa, cocok untuk kue, olesan roti, dan masakan.",
      size: "200g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 8,
      name: "Margarine Filma",
      price: 7000,
      category: "bahan-makanan",
      stock: 39,
      image: "public/foto bahan makanan/filmaa.jpg",
      description: "Margarin serbaguna dengan aroma dan rasa yang lezat, ideal untuk aneka kreasi dapur.",
      size: "200g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 9,
      name: "Margarine For Vita",
      price: 7000,
      category: "bahan-makanan",
      stock: 35,
      image: "public/foto bahan makanan/forvita.png",
      description: "Margarin bernutrisi tinggi yang cocok untuk kebutuhan memasak dan memanggang sehari-hari.",
      size: "200g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 10,
      name: "Sagu",
      price: 10000,
      category: "bahan-makanan",
      stock: 46,
      image: "public/foto bahan makanan/sagu.png",
      description: "Tepung sagu berkualitas untuk aneka jajanan tradisional seperti kue, bubur, dan pempek.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 11,
      name: "Telur",
      price: 26000,
      category: "bahan-makanan",
      stock: 100,
      image: "public/foto bahan makanan/telur.png",
      description: "Telur segar dan bergizi tinggi, sumber protein terbaik untuk menu harian keluarga.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 12,
      name: "Tepung Beras",
      price: 7500,
      category: "bahan-makanan",
      stock: 37,
      image: "public/foto bahan makanan/tepung beras.png",
      description: "Tepung halus dari beras pilihan, cocok untuk kue tradisional, bubur, dan camilan.",
      size: "500 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 13,
      name: "Tepung Ketan",
      price: 11000,
      category: "bahan-makanan",
      stock: 63,
      image: "public/foto bahan makanan/tepung ketan.png",
      description: "Tepung ketan lembut untuk membuat kue basah dan makanan khas Indonesia yang legit.",
      size: "500 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 14,
      name: "Tepung Segitiga Biru",
      price: 12000,
      category: "bahan-makanan",
      stock: 75,
      image: "public/foto bahan makanan/tepung segitiga biru.png",
      description: "Tepung terigu serbaguna dengan kualitas terbaik, pas untuk berbagai jenis masakan.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 15,
      name: "Tepung Tapioka",
      price: 7500,
      category: "bahan-makanan",
      stock: 50,
      image: "public/foto bahan makanan/tepung tapioka cap tani.png",
      description: "Tepung pati dari singkong murni, cocok untuk pempek, cilok, dan berbagai olahan tepung.",
      size: "500 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 16,
      name: "Tepung Tapioka Cap Tani",
      price: 33000,
      category: "bahan-makanan",
      stock: 47,
      image: "public/foto bahan makanan/Tepung Tapioka Cap Tani Liaw Liong.png",
      description: "Tepung tapioka asli berkualitas dari Cap Tani, menghasilkan tekstur kenyal dan lembut.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 17,
      name: "Tepung Terigu",
      price: 15000,
      category: "bahan-makanan",
      stock: 53,
      image: "public/foto bahan makanan/tepung terigu.png",
      description: "Tepung serbaguna dari gandum pilihan, cocok untuk masakan goreng dan kue.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 18,
      name: "Kecap Manis ABC",
      price: 23000,
      category: "bumbu-masakan",
      stock: 18,
      image: "public/Bumbu Masakan/ABC_KECAP_MANIS_275ML.png",
      description: "Kecap manis kental dan legit, rasa khas Indonesia yang cocok untuk semua hidangan.",
      size: "275 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 19,
      name: "Agar Agar Powder",
      price: 6000,
      category: "bumbu-masakan",
      stock: 30,
      image: "public/Bumbu Masakan/AGAR_AGAR.png",
      description: "Serbuk agar-agar untuk membuat puding dan makanan penutup yang kenyal dan segar.",
      size: "7 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 20,
      name: "Saos Extra Pedas Indofood",
      price: 10000,
      category: "bumbu-masakan",
      stock: 35,
      image: "public/Bumbu Masakan/EXTRA_PEDAS_INDOFOOD_135ml.png",
      description: "Saus cabai khas dengan tingkat kepedasan ekstra, pas untuk pecinta rasa pedas.",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 21,
      name: "Kecap Manis Indofood",
      price: 8000,
      category: "bumbu-masakan",
      stock: 121,
      image: "public/Bumbu Masakan/INDOFOOD_KECAP_BOTOL_135ML_8000-removebg-preview.png",
      description: "Kecap manis berkualitas dari Indofood dengan rasa manis gurih yang khas.",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 22,
      name: "Kaldu Jamur Totole",
      price: 11000,
      category: "bumbu-masakan",
      stock: 59,
      image: "public/Bumbu Masakan/KALDU_JAMUR_TOTOLE_11000-removebg-preview.png",
      description: "Penyedap rasa dari jamur, bebas MSG, cocok untuk vegetarian dan rasa alami masakan.",
      size: "80 gr",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 23,
      name: "Kecap Asin ABC",
      price: 6500,
      category: "bumbu-masakan",
      stock: 75,
      image: "public/Bumbu Masakan/KECAP_ASIN_131ml_6500-removebg-preview.png",
      description: "Kecap asin dengan rasa gurih seimbang, sempurna untuk tumisan dan marinasi.",
      size: "131 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 24,
      name: "Kecap Asin Cap Bulan",
      price: 23000,
      category: "bumbu-masakan",
      stock: 9,
      image: "public/Bumbu Masakan/KECAP_ASIN_620ML_23rb-removebg-preview.png",
      description: "Kecap asin legendaris dengan cita rasa tradisional khas masakan rumahan.",
      size: "620 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 25,
      name: "Kecap Manis Bango",
      price: 1000,
      category: "bumbu-masakan",
      stock: 115,
      image: "public/Bumbu Masakan/KECAP_BANGO_1rb-removebg-preview.png",
      description: "Kecap manis legendaris dari kedelai hitam pilihan, kaya rasa dan harum.",
      size: "25 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 26,
      name: "Kecap Manis Bango",
      price: 3000,
      category: "bumbu-masakan",
      stock: 156,
      image: "public/Bumbu Masakan/KECAP_BANGO_3rb-removebg-preview.png",
      description: "Kecap manis legendaris dari kedelai hitam pilihan, kaya rasa dan harum.",
      size: "77 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 27,
      name: "Ketumbar Bubuk",
      price: 1000,
      category: "bumbu-masakan",
      stock: 116,
      image: "public/Bumbu Masakan/KETUMBAR_BUBUK_125gr-removebg-preview.png",
      description: "Bumbu dapur dengan aroma khas, cocok untuk berbagai jenis masakan Indonesia.",
      size: "125 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 28,
      name: "Masako Ayam",
      price: 5000,
      category: "bumbu-masakan",
      stock: 59,
      image: "public/Bumbu Masakan/MASAKO_AYAM_123gr-removebg-preview.png",
      description: "Penyedap rasa praktis dengan cita rasa ayam yang gurih, cocok untuk semua masakan.",
      size: "123 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 29,
      name: "Masako Sapi",
      price: 13000,
      category: "bumbu-masakan",
      stock: 54,
      image: "public/Bumbu Masakan/MASAKO_SAPI_123gr-removebg-preview.png",
      description: "Kaldu sapi instan yang kuat dan gurih, menjadikan masakan lebih lezat.",
      size: "250 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 30,
      name: "Masako Sapi Renceng",
      price: 500,
      category: "bumbu-masakan",
      stock: 257,
      image: "public/Bumbu Masakan/MASAKO_SAPI_RENCENG-removebg-preview.png",
      description: "Masako rasa sapi dalam kemasan renceng praktis, cocok untuk stok dapur harian.",
      size: "8 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 31,
      name: "Mayonaise Maestro",
      price: 28000,
      category: "bumbu-masakan",
      stock: 13,
      image: "public/Bumbu Masakan/MAYONAIS_MAESTRO_1kg_28rb-removebg-preview.png",
      description: "Mayones lembut dan gurih, cocok untuk salad, burger, dan berbagai sajian modern.",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 32,
      name: "Masako Ayam Renceng",
      price: 500,
      category: "bumbu-masakan",
      stock: 235,
      image: "public/Bumbu Masakan/MSAKO_AYAM_RENCENG-removebg-preview.png",
      description: "Penyedap rasa Masako rasa ayam dalam kemasan renceng praktis, pas untuk penggunaan harian.",
      size: "8 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 33,
      name: "Racik Bumbu Ayam Goreng",
      price: 2000,
      category: "bumbu-masakan",
      stock: 100,
      image: "public/Bumbu Masakan/RACIK_AYAM_GORENG-removebg-preview.png",
      description: "Bumbu instan yang memudahkan memasak ayam goreng gurih ala rumahan.",
      size: "26 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 34,
      name: "Racik Bumbu Ayam Goreng Rempah",
      price: 2000,
      category: "bumbu-masakan",
      stock: 95,
      image: "public/Bumbu Masakan/RACIK_AYAM_GORENG_REMPAH-removebg-preview.png",
      description: "Dilengkapi rempah pilihan, bumbu ini membuat ayam goreng semakin harum dan lezat.",
      size: "30 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 35,
      name: "Racik Bumbu Sayur Lodeh",
      price: 2000,
      category: "bumbu-masakan",
      stock: 65,
      image: "public/Bumbu Masakan/RACIK_SAYUR_LODEH-removebg-preview.png",
      description: "Bumbu siap pakai untuk membuat sayur lodeh dengan rasa gurih khas nusantara.",
      size: "25 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 36,
      name: "Racik Bumbu Tempe & Tahu Goreng",
      price: 2000,
      category: "bumbu-masakan",
      stock: 83,
      image: "public/Bumbu Masakan/RACIK_TEMPE___TAHU_GORENG-removebg-preview.png",
      description: "Bumbu praktis untuk menghasilkan tempe dan tahu goreng yang gurih dan renyah.",
      size: "20 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 37,
      name: "Sajiku Bumbu Sayur Asem",
      price: 2000,
      category: "bumbu-masakan",
      stock: 89,
      image: "public/Bumbu Masakan/SAJIKU_SAYUR_ASEM_30gr-removebg-preview.png",
      description: "Bumbu instan dari Sajiku dengan rasa asam segar khas sayur asem tradisional.",
      size: "30 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 38,
      name: "Saos Extra Hot DelMonte",
      price: 12000,
      category: "bumbu-masakan",
      stock: 77,
      image: "public/Bumbu Masakan/SAOS_EXTRA_HOT_DELMONTE_265ml_12000-removebg-preview.png",
      description: "Saus cabai dengan sensasi pedas lebih, cocok untuk penggemar rasa ekstrem.",
      size: "265 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 39,
      name: "Sarden ABC",
      price: 28000,
      category: "bumbu-masakan",
      stock: 68,
      image: "public/Bumbu Masakan/SARDEN_ABC_425gr_27_5rb___155gr___12rb-removebg-preview.png",
      description: "Ikan sarden dalam saus tomat lezat, praktis dan cocok sebagai lauk siap saji.",
      size: "425 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 40,
      name: "Sarden ABC",
      price: 12000,
      category: "bumbu-masakan",
      stock: 75,
      image: "public/Bumbu Masakan/SARDEN_ABC_425gr_27_5rb___155gr___12rb-removebg-preview.png",
      description: "Ikan sarden dalam saus tomat lezat, praktis dan cocok sebagai lauk siap saji.",
      size: "155 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 41,
      name: "Sasa",
      price: 3000,
      category: "bumbu-masakan",
      stock: 25,
      image: "public/Bumbu Masakan/SASA_50gr-removebg-preview.png",
      description: "Penyedap rasa legendaris Indonesia untuk menambah kelezatan aneka masakan.",
      size: "50 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 42,
      name: "Saos Sambal ABC",
      price: 8000,
      category: "bumbu-masakan",
      stock: 47,
      image: "public/Bumbu Masakan/SAUS_ABC_135ml_8000-removebg-preview.png",
      description: "Saus sambal dengan cita rasa pedas-manis seimbang, cocok untuk segala hidangan.",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 43,
      name: "Saus ABC Extreme Pedas",
      price: 16000,
      category: "bumbu-masakan",
      stock: 35,
      image: "public/Bumbu Masakan/SAUS_BOTOL_270ml_ABC_EXTREME_PEDAS_16000-removebg-preview.png",
      description: "Varian saus sambal dari ABC dengan tingkat kepedasan ekstra untuk penikmat pedas sejati.",
      size: "270 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 44,
      name: "Saus Saset Delmonte /3pcs",
      price: 1000,
      category: "bumbu-masakan",
      stock: 325,
      image: "public/Bumbu Masakan/SAUS_SASET_DELMONTE_2_500-removebg-preview.png",
      description: "Saus sambal praktis kemasan sachet, ideal untuk bekal atau keperluan sekali pakai.",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 45,
      name: "Saori Saus Tiram",
      price: 3000,
      category: "bumbu-masakan",
      stock: 115,
      image: "public/Bumbu Masakan/SAUS_TIRAM_SAORI-removebg-preview.png",
      description: "Saus tiram berkualitas dengan rasa gurih manis khas masakan oriental.",
      size: "23 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 46,
      name: "Saus Tomat ABC",
      price: 8500,
      category: "bumbu-masakan",
      stock: 75,
      image: "public/Bumbu Masakan/SAUS_TOMAT_135ml_8500-removebg-preview.png",
      description: "Saus tomat segar dengan rasa manis alami, cocok untuk pendamping makanan goreng.",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 47,
      name: "Saus Tomat ABC",
      price: 15000,
      category: "bumbu-masakan",
      stock: 70,
      image: "public/Bumbu Masakan/SAUS_TOMAT_BOTOL_ABC_15000-removebg-preview.png",
      description: "Saus tomat segar dengan rasa manis alami, cocok untuk pendamping makanan goreng.",
      size: "275 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 48,
      name: "Susu Kental Manis Cap Enak",
      price: 12000,
      category: "bumbu-masakan",
      stock: 95,
      image: "public/Bumbu Masakan/SKM_ENAAK_12rb-removebg-preview.png",
      description: "Susu kental manis serbaguna untuk minuman, roti, atau olahan kue dan dessert.",
      size: "370 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 49,
      name: "Tepung Kobe Kentucky",
      price: 3000,
      category: "bumbu-masakan",
      stock: 75,
      image: "public/Bumbu Masakan/TEPUNG_KOBE_KENTUCKY-removebg-preview.png",
      description: "Tepung bumbu siap pakai untuk ayam goreng ala kentucky yang renyah dan gurih.",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 50,
      name: "Sajiku Tepung Serbaguna",
      price: 3000,
      category: "bumbu-masakan",
      stock: 60,
      image: "public/Bumbu Masakan/TEPUNG_SAJIKU-removebg-preview.png",
      description: "Tepung bumbu dari Sajiku untuk membuat gorengan renyah dengan rasa lezat.",
      size: "40 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 51,
      name: "Terasi Udang",
      price: 500,
      category: "bumbu-masakan",
      stock: 95,
      image: "public/Bumbu Masakan/TERASI-removebg-preview.png",
      description: "Terasi berkualitas dari udang pilihan, memperkuat aroma dan rasa masakan tradisional.",
      size: "4 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 52,
      name: "Kopi Bubuk Semendo",
      price: 18000,
      category: "minuman",
      stock: 65,
      image: "public/minuman/KOPI_BUBUK_18rb-removebg-preview-removebg-preview.png",
      description: "Kopi bubuk khas daerah Semendo, aromanya kuat dan rasanya pekat.",
      size: "100 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 53,
      name: "Kopi Roda 666",
      price: 20000,
      originalPrice: 22000,
      category: "minuman",
      stock: 55,
      image: "public/minuman/KOPI_BUBUK_666_21_5rb-removebg-preview.png",
      description: "Kopi klasik dengan cita rasa khas, cocok untuk penikmat kopi hitam tradisional.",
      size: "160 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 54,
      name: "Aqua Botol",
      price: 8000,
      originalPrice: 10000,
      category: "minuman",
      stock: 10,
      image: "public/minuman/AQUA_1_5L-removebg-preview.png",
      description: "Air mineral kemasan botol, jernih dan segar untuk dikonsumsi kapan saja.",
      size: "1,5 l",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 55,
      name: "Chocodrink",
      price: 2000,
      category: "minuman",
      stock: 25,
      image: "public/minuman/CHOCODRINK-removebg-preview.png",
      description: "Minuman coklat instan yang nikmat disajikan panas maupun dingin.",
      size: "28 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 56,
      name: "Chocolatos Coklat",
      price: 2000,
      category: "minuman",
      stock: 20,
      image: "public/minuman/CHOCOLATOS_COKLAT-removebg-preview.png",
      description: "Minuman coklat premium dengan rasa creamy yang disukai segala usia.",
      size: "28 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 57,
      name: "Chocolatos Matcha",
      price: 2000,
      category: "minuman",
      stock: 32,
      image: "public/minuman/CHOCOLATOS_MATCHA-removebg-preview.png",
      description: "Serbuk minuman rasa matcha, perpaduan teh hijau yang lembut dan menyegarkan.",
      size: "28 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 58,
      name: "Energen Coklat",
      price: 2500,
      category: "minuman",
      stock: 46,
      image: "public/minuman/ENERGEN_COKLAT-removebg-preview.png",
      description: "Sereal instan bergizi rasa coklat, pas untuk sarapan cepat dan sehat.",
      size: "35 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 59,
      name: "Energen Kacang Hijau",
      price: 2500,
      category: "minuman",
      stock: 43,
      image: "public/minuman/ENERGEN_KACANG_HIJAU-removebg-preview-removebg-preview.png",
      description: "Minuman sereal rasa kacang hijau dengan kandungan vitamin dan serat.",
      size: "32 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 60,
      name: "Energen Vanila",
      price: 2500,
      category: "minuman",
      stock: 55,
      image: "public/minuman/ENERGEN_VANILA-removebg-preview.png",
      description: "Energen rasa vanila yang manis dan lembut, pilihan sehat untuk sarapan praktis.",
      size: "34 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 61,
      name: "Floridina",
      price: 3000,
      category: "minuman",
      stock: 87,
      image: "public/minuman/FLORIDINA-removebg-preview.png",
      description: "Minuman jeruk segar dengan bulir asli, pas untuk melepas dahaga di cuaca panas.",
      size: "350 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 62,
      name: "Aqua Galon",
      price: 18000,
      category: "minuman",
      stock: 5,
      image: "public/minuman/GALON_AQUA-removebg-preview (1).png",
      description: "Air mineral dalam kemasan galon 19 liter, cocok untuk kebutuhan rumah tangga dan kantor.",
      size: "19 l",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 63,
      name: "Aquali 1 Dus",
      price: 15000,
      category: "minuman",
      stock: 7,
      image: "",
      description: "air mineral dalam kemasan cup, menyegarkan dan cocok untuk berbagai acara.",
      size: "13 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 64,
      name: "Golda Coffee",
      price: 3500,
      category: "minuman",
      stock: 113,
      image: "public/minuman/GOLDA-removebg-preview.png",
      description: "Kopi susu kemasan siap minum dengan rasa manis dan aroma kopi yang khas.",
      size: "200 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 65,
      name: "Good day Cappucino",
      price: 3000,
      category: "minuman",
      stock: 95,
      image: "public/minuman/GOODDAY_CAPPUCINO-removebg-preview.png",
      description: "Kopi instan dengan foam lembut dan rasa cappuccino yang creamy.",
      size: "25 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 66,
      name: "Kopikap",
      price: 1000,
      category: "minuman",
      stock: 110,
      image: "public/minuman/KOPIKAP-removebg-preview.png",
      description: "Kopi bubuk lokal dengan rasa yang kuat dan harga ekonomis.",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 67,
      name: "Le Minerale",
      price: 4000,
      category: "minuman",
      stock: 90,
      image: "public/minuman/LE_MINERALE_600_ml-removebg-preview.png",
      description: "Air mineral sehat dengan kandungan mineral alami dan rasa segar.",
      size: "600 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 68,
      name: "Aquali Cup",
      price: 1000,
      category: "minuman",
      stock: 147,
      image: "public/minuman/MINERAL_CUP__1_-removebg-preview.png",
      description: "Air minum dalam gelas kemasan plastik, cocok untuk acara atau keperluan praktis.",
      size: "220 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 69,
      name: "Mizone",
      price: 6000,
      category: "minuman",
      stock: 55,
      image: "public/minuman/MIZONE_CRANBERRY___LYCHEE_LEMON-removebg-preview.png",
      description: "Minuman isotonik rasa buah, membantu menggantikan ion tubuh yang hilang.",
      size: "250 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 70,
      name: "Pop Ice Cappucino",
      price: 2000,
      category: "minuman",
      stock: 60,
      image: "public/minuman/POP_ICE_CAPPUCINO-removebg-preview.png",
      description: "Minuman serbuk rasa cappuccino manis, bisa disajikan dingin maupun panas.",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 71,
      name: "Pop Ice Choco Cream",
      price: 2000,
      category: "minuman",
      stock: 98,
      image: "public/minuman/POP_ICE_CHOCOCREAM-removebg-preview.png",
      description: "Minuman serbuk rasa cokelat creamy yang menyegarkan, cocok dinikmati dingin kapan saja.",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 72,
      name: "Pop Ice Permen Karet",
      price: 2000,
      category: "minuman",
      stock: 67,
      image: "public/minuman/POP_ICE_PERMEN_KARET-removebg-preview.png",
      description: "Minuman serbuk rasa permen karet yang manis dan unik, disukai anak-anak.",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 73,
      name: "Pop Ice Strawberry",
      price: 2000,
      category: "minuman",
      stock: 80,
      image: "public/minuman/POP_ICE_STOBERI-removebg-preview.png",
      description: "Minuman serbuk dengan rasa stroberi yang segar, cocok untuk pelepas dahaga.",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 74,
      name: "Pop Ice Taro",
      price: 2000,
      category: "minuman",
      stock: 95,
      image: "public/minuman/POP_ICE_TARO-removebg-preview.png",
      description: "Minuman serbuk rasa talas khas yang lembut dan lezat.",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 75,
      name: "Power F",
      price: 1000,
      category: "minuman",
      stock: 75,
      image: "public/minuman/POWER_F-removebg-preview.png",
      description: "Minuman energi instan yang menyegarkan, bantu tingkatkan stamina saat beraktivitas.",
      size: "180 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 76,
      name: "Kental Manis Frisian Flag Coklat",
      price: 2000,
      category: "minuman",
      stock: 115,
      image: "public/minuman/SKM_SASET_COKLAT-removebg-preview.png",
      description: "Susu kental manis rasa cokelat yang cocok untuk campuran minuman dan makanan.",
      size: "38 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 77,
      name: "Kental Manis Saset Frisian Flag",
      price: 2000,
      category: "minuman",
      stock: 100,
      image: "public/minuman/SKM_SASET_PUTIH-removebg-preview.png",
      description: "Susu kental manis kemasan saset praktis, ideal untuk sekali pakai.",
      size: "38 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 78,
      name: "Bonteh",
      price: 4000,
      category: "minuman",
      stock: 35,
      image: "public/minuman/TEH_MANIS_BONTEH-removebg-preview.png",
      description: "Minuman teh celup tradisional, cocok untuk relaksasi dan teman makan.",
      size: "330 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 79,
      name: "Teh Pucuk Harum",
      price: 4000,
      category: "minuman",
      stock: 70,
      image: "public/minuman/TEH_PUCUK_HARUM-removebg-preview-removebg-preview.png",
      description: "Minuman teh dalam botol dengan rasa segar dan manis alami.",
      size: "350 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 80,
      name: "Teh Celup Sariwangi",
      price: 1500,
      category: "minuman",
      stock: 45,
      image: "public/minuman/TEH_SARIWANGI_SASET-removebg-preview.png",
      description: "Teh celup klasik dengan aroma khas dan rasa nikmat.",
      size: "38 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 81,
      name: "TOP Coffee Gula Aren",
      price: 2500,
      category: "minuman",
      stock: 75,
      image: "public/minuman/TOP_GULA_AREN-removebg-preview.png",
      description: "Kopi instan dengan gula aren asli, memberikan cita rasa khas nusantara.",
      size: "22 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 82,
      name: "Torabika Moka",
      price: 2500,
      category: "minuman",
      stock: 60,
      image: "public/minuman/TORA_MOKA-removebg-preview.png",
      description: "Kopi instan rasa moka yang manis dan nikmat, cocok untuk pagi hari.",
      size: "28 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 83,
      name: "Amplop 1pcs",
      price: 500,
      category: "nonfood",
      stock: 195,
      image: "public/NonFood/AMPLOP-removebg-preview (1).png",
      description: "Amplop polos serbaguna untuk kebutuhan surat, dokumen, atau keperluan pribadi.",
      size: "6 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 84,
      name: "Baterai ABC",
      price: 4000,
      category: "nonfood",
      stock: 63,
      image: "public/NonFood/BATERAII-removebg-preview (1).png",
      description: "Baterai ukuran AA yang tahan lama, cocok untuk berbagai perangkat elektronik.",
      size: "17 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 85,
      name: "Charm Safenight",
      price: 3000,
      category: "nonfood",
      stock: 44,
      image: "public/NonFood/CHARM_SAFENIGHT_29cm-removebg-preview (1).png",
      description: "Pembalut malam hari dengan daya serap ekstra, memberikan kenyamanan sepanjang malam.",
      size: "29 cm",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 86,
      name: "Charm ExtraMaxi Wing",
      price: 2500,
      category: "nonfood",
      stock: 60,
      image: "public/NonFood/CHARM_SAFENIGHT_29cm-removebg-preview (1).png",
      description: "Pembalut siang hari dengan sayap, menyerap cepat dan mencegah bocor.",
      size: "22 cm",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 87,
      name: "Pasta Gigi Ciptadent",
      price: 4000,
      category: "nonfood",
      stock: 35,
      image: "public/Nonfood/CIPTADENT_75gr_4000___120gr_7500-removebg-preview (1).png",
      description: "Pasta gigi dengan perlindungan menyeluruh untuk kesehatan gigi dan mulut.",
      size: "75 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 88,
      name: "Pasta Gigi Ciptadent",
      price: 7500,
      category: "nonfood",
      stock: 45,
      image: "public/Nonfood/CIPTADENT_75gr_4000___120gr_7500-removebg-preview.png",
      description: "Pasta gigi dengan perlindungan menyeluruh untuk kesehatan gigi dan mulut.",
      size: "120 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 89,
      name: "Conditioner Saset Pantene",
      price: 1000,
      category: "nonfood",
      stock: 98,
      image: "public/NonFood/CONDITIONER_SASET_PANTENE-removebg-preview (1).png",
      description: "Kondisioner dalam kemasan praktis, melembutkan dan menutrisi rambut.",
      size: "10 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 90,
      name: "Detergen Daia",
      price: 1000,
      category: "nonfood",
      stock: 100,
      image: "public/Nonfood/DETERGEN_DAIA_1000-removebg-preview.png",
      description: "Detergen bubuk dengan wangi menyegarkan dan daya bersih maksimal.",
      size: "47 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 91,
      name: "Downy ",
      price: 22000,
      category: "nonfood",
      stock: 79,
      image: "public/Nonfood/DOWNY_22000-removebg-preview.png",
      description: "Pelembut pakaian dengan aroma tahan lama, menjadikan cucian lebih harum.",
      size: "600 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 92,
      name: "Gentle Gen",
      price: 1000,
      category: "nonfood",
      stock: 110,
      image: "public/Nonfood/GENTLE_GEN-removebg-preview (1).png",
      description: "Pembersih tubuh atau pakaian lembut, cocok untuk kulit sensitif.",
      size: "80 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 93,
      name: "Kapas Wajah Selection",
      price: 6000,
      category: "nonfood",
      stock: 50,
      image: "public/Nonfood/KAPAS_SELECTION_6000-removebg-preview.png",
      description: "Kapas lembut dan tebal, ideal untuk membersihkan wajah atau keperluan kosmetik.",
      size: "35 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 94,
      name: "Kapur Ajaib",
      price: 4000,
      category: "nonfood",
      stock: 20,
      image: "public/Nonfood/KAPUR_AJAIB_4rb-removebg-preview (1).png",
      description: "Pembasmi serangga berbentuk kapur, efektif mengusir semut dan kecoa.",
      size: "4 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 95,
      name: "Kapur Barus",
      price: 6000,
      category: "nonfood",
      stock: 43,
      image: "public/Nonfood/KAPUR_BARUS-removebg-preview.png",
      description: "Pengharum lemari dan pelindung pakaian dari ngengat dengan aroma segar.",
      size: "35 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 96,
      name: "Kispray",
      price: 500,
      category: "nonfood",
      stock: 115,
      image: "public/Nonfood/KISPRAY_-removebg-preview (1).png",
      description: "Pelicin pakaian dan pewangi yang memudahkan setrika dan menyegarkan pakaian.",
      size: "6 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 97,
      name: "Lampu Lanbo 10 Watt",
      price: 12000,
      category: "nonfood",
      stock: 15,
      image: "public/Nonfood/LAMPU_10w___15w-removebg-preview (1).png",
      description: "Lampu hemat energi dengan cahaya terang untuk penerangan rumah.",
      size: "10 W",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 98,
      name: "Lampu Lanbo 15 Watt",
      price: 17000,
      category: "nonfood",
      stock: 15,
      image: "public/Nonfood/LAMPU_10w___15w-removebg-preview (1).png",
      description: "Lampu watt lebih besar, ideal untuk ruangan yang membutuhkan pencahayaan ekstra.",
      size: "15 W",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 99,
      name: "Lem Kertas Glikol",
      price: 2000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/LEM_KERTAS-removebg-preview (1).png",
      description: "Lem cair untuk menempelkan kertas, cocok untuk anak sekolah.",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 100,
      name: "Lem Korea",
      price: 7000,
      category: "nonfood",
      stock: 25,
      image: "public/Nonfood/LEM_SYAITONNIROJIM-removebg-preview (1).png",
      description: "Lem kuat serbaguna dengan daya rekat tinggi, cocok untuk memperbaiki berbagai bahan.",
      size: "10 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 101,
      name: "Mama Lemon",
      price: 24000,
      category: "nonfood",
      stock: 9,
      image: "public/Nonfood/MAMA_LEMON_1_5kg_24000-removebg-preview.png",
      description: "Sabun cuci piring dengan daya angkat lemak tinggi dan aroma jeruk segar.",
      size: "1,5 L",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 102,
      name: "Obat Nyamuk",
      price: 4000,
      category: "nonfood",
      stock: 30,
      image: "public/Nonfood/OBAT_NYAMUK_4000__kotak-removebg-preview.png",
      description: "Obat pengusir nyamuk dalam bentuk bakar, efektif melindungi keluarga.",
      size: "100 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 103,
      name: "Pena Standard Castello",
      price: 2000,
      category: "nonfood",
      stock: 30,
      image: "public/Nonfood/PENA-removebg-preview (1).png",
      description: "Pulpen berkualitas dengan tinta lancar, cocok untuk menulis harian.",
      size: "10 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 104,
      name: "Pepsodent",
      price: 10000,
      category: "nonfood",
      stock: 35,
      image: "public/Nonfood/PEPSODENT_120gr_10000-removebg-preview.png",
      description: "Pasta gigi dengan perlindungan ganda, menjaga kesehatan gigi dan napas segar.",
      size: "120 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 105,
      name: "Pepsodent",
      price: 14000,
      category: "nonfood",
      stock: 23,
      image: "public/Nonfood/PEPSODENT_190gr_14000-removebg-preview.png",
      description: "Pasta gigi dengan perlindungan ganda, menjaga kesehatan gigi dan napas segar.",
      size: "190 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 106,
      name: "Downy Saset",
      price: 500,
      category: "nonfood",
      stock: 95,
      image: "public/Nonfood/PEWANGI_PAKAIAN_DOWNY-removebg-preview (1).png",
      description: "Pelembut pakaian dalam kemasan saset, ekonomis dan wangi tahan lama.",
      size: "8 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 107,
      name: "Downy Extra Saset",
      price: 1000,
      category: "nonfood",
      stock: 78,
      image: "public/Nonfood/PEWANGI_PAKAIAN_DOWNY_1rb-removebg-preview (1).png",
      description: "Varian ekstra wangi dari Downy dalam bentuk saset praktis.",
      size: "24 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 108,
      name: "Sabun Batang GIV",
      price: 3000,
      category: "nonfood",
      stock: 50,
      image: "public/Nonfood/SABUN_BTG_3000-removebg-preview.png",
      description: "Sabun batang dengan aroma bunga yang lembut dan menyegarkan.",
      size: "72 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 109,
      name: "Sabun Batang Harmony",
      price: 3000,
      category: "nonfood",
      stock: 63,
      image: "public/Nonfood/SABUN_BTG_3000__1_-removebg-preview.png",
      description: "Sabun wangi dengan busa lembut untuk kulit bersih dan harum.",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 110,
      name: "Sabun Batang Fres",
      price: 4000,
      category: "nonfood",
      stock: 60,
      image: "public/Nonfood/SABUN_BTG_4000__1_-removebg-preview.png",
      description: "Sabun batang dengan aroma segar dan lembut di kulit.",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 111,
      name: "Sabun Batang Lifebuoy",
      price: 4000,
      category: "nonfood",
      stock: 97,
      image: "public/Nonfood/SABUN_BTG_4000-removebg-preview.png",
      description: "Sabun antibakteri yang melindungi kulit dari kuman penyebab penyakit.",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 112,
      name: "Sabun Batang Lux",
      price: 4500,
      category: "nonfood",
      stock: 124,
      image: "public/Nonfood/SABUN_BTG_4500-removebg-preview.png",
      description: "Sabun mandi elegan dengan aroma mewah dan pelembap untuk kulit halus.",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 113,
      name: "Sabun Cair Glow & Lovely",
      price: 5000,
      category: "nonfood",
      stock: 67,
      image: "public/Nonfood/SABUN_CAIR_GLOW_LOVELY_5000-removebg-preview.png",
      description: "Pembersih wajah yang membantu mencerahkan kulit dan mengangkat kotoran.",
      size: "85 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 114,
      name: "Sabun Cair Lifebuoy",
      price: 5000,
      category: "nonfood",
      stock: 45,
      image: "public/Nonfood/SABUN_CAIR_LIFEBUOY_5000-removebg-preview.png",
      description: "Sabun cair antibakteri untuk seluruh keluarga, melindungi dari kuman.",
      size: "85 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 115,
      name: "Sabun Cair Shinzui",
      price: 5000,
      category: "nonfood",
      stock: 48,
      image: "public/Nonfood/SABUN_CAIR_SHINZUI_5000-removebg-preview.png",
      description: "Sabun cair dengan bahan alami untuk mencerahkan dan melembapkan kulit.",
      size: "85 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 116,
      name: "Sabun Colek Ekonomi",
      price: 1000,
      category: "nonfood",
      stock: 70,
      image: "public/Nonfood/SABUN_COLEK_EKONOMI_1000-removebg-preview.png",
      description: "Sabun cuci serbaguna untuk membersihkan noda membandel.",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 117,
      name: "Sabut Cuci Piring",
      price: 5000,
      category: "nonfood",
      stock: 25,
      image: "public/Nonfood/SABUT_CUCI_PIRING_5000-removebg-preview.png",
      description: "Alat pembersih piring berbahan spons kasar, cocok untuk menggosok peralatan dapur.",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 118,
      name: "Sabut Jaring",
      price: 5000,
      category: "nonfood",
      stock: 55,
      image: "public/Nonfood/SABUT_STAINLESS_3000-removebg-preview.png",
      description: "Sabut halus berbentuk jaring untuk mencuci tanpa menggores permukaan.",
      size: "3 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 119,
      name: "Sabut Stainless",
      price: 3000,
      category: "nonfood",
      stock: 35,
      image: "public/Nonfood/SABUT_JARING_5000-removebg-preview.png",
      description: "Sabut berbahan baja tahan karat, efektif membersihkan kotoran membandel.",
      size: "3 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 120,
      name: "Shampoo Saset Clear",
      price: 1000,
      category: "nonfood",
      stock: 200,
      image: "public/Nonfood/SHAMPOO_SASET_CLEAR-removebg-preview (1).png",
      description: "Shampo dalam kemasan praktis, membersihkan dan menyegarkan kulit kepala.",
      size: "9 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 121,
      name: "Shampoo Saset Clear Anti Ketombe & Rambut Rontok",
      price: 1000,
      category: "nonfood",
      stock: 250,
      image: "public/Nonfood/SHAMPOO_SASET_CLEAR_OREN-removebg-preview (1).png",
      description: "Shampo anti ketombe dan rambut rontok, dalam kemasan sekali pakai.",
      size: "9 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 122,
      name: "Shampoo Saset Head & Shoulders",
      price: 1000,
      category: "nonfood",
      stock: 100,
      image: "public/Nonfood/SHAMPOO_SASET_HEAD_SHOULDERS-removebg-preview (1).png",
      description: "Shampo terkenal untuk ketombe, menyegarkan dan menenangkan kulit kepala.",
      size: "9 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 123,
      name: "Shampoo Saset Lifebuoy",
      price: 1000,
      category: "nonfood",
      stock: 200,
      image: "public/Nonfood/SHAMPOO_SASET_LIFEBUOY_-removebg-preview.png",
      description: "Shampo praktis untuk perawatan rambut harian, membantu membersihkan kulit kepala dari kotoran.",
      size: "9 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 124,
      name: "Shampoo Saset Pantene",
      price: 1000,
      category: "nonfood",
      stock: 130,
      image: "public/Nonfood/SHAMPOO_SASET_PANTENE_AVOCADO-removebg-preview (1).png",
      description: "Shampo dalam kemasan saset, membuat rambut lebih kuat dan berkilau.",
      size: "9 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 125,
      name: "Shampoo Saset Pantene Hijau",
      price: 1000,
      category: "nonfood",
      stock: 170,
      image: "public/Nonfood/SHAMPOO_SASET_PANTENE_HIJAU-removebg-preview (1).png",
      description: "Varian herbal dari Pantene, memberikan kesegaran alami dan mengurangi kerontokan.",
      size: "9 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 126,
      name: "Shampoo Saset Sunsilk",
      price: 1000,
      category: "nonfood",
      stock: 155,
      image: "public/Nonfood/SHAMPOO_SASET_SUNSILK-removebg-preview (1).png",
      description: "Shampoo kemasan saset untuk rambut anti ketombe dan wangi sepanjang hari",
      size: "9 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 127,
      name: "Sikat Gigi Formula",
      price: 4000,
      category: "nonfood",
      stock: 25,
      image: "public/Nonfood/SIKAT_GIGI_FORMULA_4000-removebg-preview.png",
      description: "Sikat gigi ergonomis dengan bulu lembut, membersihkan gigi secara maksimal.",
      size: "15 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 128,
      name: "Soklin Jumbo",
      price: 1000,
      category: "nonfood",
      stock: 50,
      image: "public/Nonfood/SO_KLIN_JUMBO-removebg-preview (1).png",
      description: "Detergen ukuran besar, ampuh mengangkat noda dan memberi aroma tahan lama.",
      size: "40 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 129,
      name: "Soffell",
      price: 1000,
      category: "nonfood",
      stock: 50,
      image: "public/Nonfood/SOFELL_JERUK-removebg-preview (1).png",
      description: "Lotion anti nyamuk dengan aroma lembut, menjaga kulit dari gigitan nyamuk.",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 130,
      name: "Soklin Lantai",
      price: 1000,
      category: "nonfood",
      stock: 25,
      image: "public/Nonfood/SOKLIN_LANTAI_1000-removebg-preview.png",
      description: "Pembersih lantai dengan aroma menyegarkan dan daya bersih tinggi.",
      size: "52 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 131,
      name: "Tali Rapia",
      price: 2000,
      category: "nonfood",
      stock: 15,
      image: "public/Nonfood/TALI_RAPIA_2000-removebg-preview.png",
      description: "Tali serbaguna untuk kebutuhan mengikat barang atau keperluan rumah tangga.",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 132,
      name: "Tissue Jolly",
      price: 10000,
      category: "nonfood",
      stock: 40,
      image: "public/Nonfood/TISSUE_JOLLY_10000-removebg-preview.png",
      description: "Tisu dengan tekstur lembut, cocok untuk wajah maupun kebutuhan harian.",
      size: "250 Sheets",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 133,
      name: "Lem Korea",
      price: 7000,
      category: "nonfood",
      stock: 25,
      image: "public/Nonfood/LEM_SYAITONNIROJIM-removebg-preview (1).png",
      description: "Lem kuat serbaguna dengan daya rekat tinggi, cocok untuk memperbaiki berbagai bahan.",
      size: "10 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 134,
      name: "Bihun",
      price: 5000,
      category: "mie",
      stock: 33,
      image: "public/mie/BIHUN-removebg-preview.png",
      description: "Bihun kering yang cocok dijadikan pelengkap masakan seperti soto dan bakso.",
      size: "100 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 135,
      name: "Indomie Ayam Bawang",
      price: 3500,
      category: "mie",
      stock: 57,
      image: "public/mie/INDOMIE_AYAM_BAWANG_3500-removebg-preview.png",
      description: "Mie instan kuah dengan rasa gurih ayam dan bawang khas.",
      size: "69 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 136,
      name: "Indomie Ayam Geprek",
      price: 3500,
      category: "mie",
      stock: 41,
      image: "public/mie/INDOMIE_AYAM_GEPREK_3500-removebg-preview.png",
      description: "Mie instan pedas dengan cita rasa ayam geprek kekinian.",
      size: "85 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 137,
      name: "Indomie Goreng",
      price: 3500,
      category: "mie",
      stock: 83,
      image: "public/mie/INDOMIE_GORENG_3500-removebg-preview.png",
      description: "Mie instan goreng legendaris dengan bumbu lengkap dan nikmat.",
      size: "80 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 138,
      name: "Indomie Aceh",
      price: 3500,
      category: "mie",
      stock: 53,
      image: "public/mie/INDOMIE_GORENG_ACEH_3500-removebg-preview.png",
      description: "Mie instan dengan rasa khas mie Aceh yang pedas dan kaya rempah.",
      size: "90 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 139,
      name: "Indomie Goreng Jumbo",
      price: 4500,
      category: "mie",
      stock: 32,
      image: "public/mie/INDOMIE_GORENG_JUMBO_4500-removebg-preview.png",
      description: "Varian besar dari Indomie Goreng, cocok untuk porsi lebih banyak.",
      size: "129 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 140,
      name: "Indomie Kuah Kari Ayam",
      price: 3500,
      category: "mie",
      stock: 53,
      image: "public/mie/INDOMIE_KUAH_KARI_AYAM_3500-removebg-preview.png",
      description: "Mie instan dengan kuah kari ayam yang gurih dan hangat.",
      size: "72 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 141,
      name: "Indomie Kuah Soto Mie",
      price: 3500,
      category: "mie",
      stock: 44,
      image: "public/mie/INDOMIE_KUAH_SOTO_3500-removebg-preview.png",
      description: "Mie instan rasa soto mie, perpaduan kuah segar dan gurih.",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 142,
      name: "Indomie Mi Celor",
      price: 3500,
      category: "mie",
      stock: 72,
      image: "public/mie/INDOMIE_MI_CELOR_3500-removebg-preview.png",
      description: "Mie instan khas Palembang dengan rasa unik dan creamy.",
      size: "75 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 143,
      name: "Indomie Rendang",
      price: 3500,
      category: "mie",
      stock: 36,
      image: "public/mie/INDOMIE_RENDANG_3500-removebg-preview.png",
      description: "Mie instan dengan cita rasa rendang khas Minang yang kuat dan pedas.",
      size: "91 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 144,
      name: "Mie Gaga 100",
      price: 3500,
      category: "mie",
      stock: 68,
      image: "public/mie/MIE_GAGA_3500-removebg-preview.png",
      description: "Mie instan pedas dengan level kepedasan yang menantang.",
      size: "85 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 145,
      name: "Mie Sedaap Soto",
      price: 3500,
      category: "mie",
      stock: 44,
      image: "public/mie/MIE_SEDAAP_KUAH_SOTO_3500-removebg-preview.png",
      description: "Mie instan dengan rasa soto segar dan gurih dengan extra koya.",
      size: "76 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 146,
      name: "Mie Telor A1",
      price: 6000,
      category: "mie",
      stock: 57,
      image: "public/mie/MIE_TELOR-removebg-preview.png",
      description: "Mie telur berkualitas untuk berbagai jenis masakan.",
      size: "180 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 147,
      name: "Pop Mie Baso",
      price: 5000,
      category: "mie",
      stock: 30,
      image: "public/mie/POP_MIE_5000-removebg-preview.png",
      description: "Mie instan dalam cup praktis dengan rasa bakso, cocok dinikmati kapan saja.",
      size: "75 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 148,
      name: "Sarimie Isi 2 Ayam Kecap",
      price: 4500,
      category: "mie",
      stock: 43,
      image: "public/mie/SARIMI_ISI_2_AYAM_KECAP_4500-removebg-preview.png",
      description: "Mie instan isi 2 dengan rasa ayam kecap yang manis gurih.",
      size: "126 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 149,
      name: "Sohun",
      price: 3000,
      category: "mie",
      stock: 80,
      image: "public/mie/SOHUN-removebg-preview.png",
      description: "Sohun kering cocok untuk campuran sup, tumisan, atau bakso.",
      size: "50 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 150,
      name: "Supermie Sup Sayuran",
      price: 2000,
      category: "mie",
      stock: 55,
      image: "public/mie/SUPERMI_KUAH_SUP_SAYURAN_2000-removebg-preview.png",
      description: "Mie instan rasa sayuran dengan kuah yang ringan dan segar.",
      size: "65 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 151,
      name: "Bakpia",
      price: 2000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "Kue isi kacang hijau yang lembut dan manis, khas oleh-oleh Indonesia.",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 152,
      name: "Chocolatos",
      price: 1000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "Camilan wafer cokelat dan keju dengan isian lembut dan rasa premium.",
      size: "13 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 153,
      name: "Biskuit Coco Puff",
      price: 10000,
      category: "jajanan",
      stock: 10,
      image: "public/jajanan/CHOCOPUFF-removebg-preview.png",
      description: "Biskuit ringan dengan rasa coklat, cocok untuk camilan anak-anak.",
      size: "230 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 154,
      name: "Crispy Crackers",
      price: 12000,
      category: "jajanan",
      stock: 15,
      image: "public/jajanan/CHOCOPUFF-removebg-preview.png",
      description: "Biskuit renyah yang pas untuk menemani teh atau kopi.",
      size: "250 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 155,
      name: "Hatari Malkist Plain",
      price: 7000,
      category: "jajanan",
      stock: 15,
      image: "public/jajanan/GABIN_HATARI_PLAIN-removebg-preview.png",
      description: "Biskuit Malkist gurih dan renyah, cocok untuk camilan keluarga.",
      size: "245 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 156,
      name: "Hatari Malkist",
      price: 7000,
      category: "jajanan",
      stock: 20,
      image: "public/jajanan/GABIN_HATARI_MALKIST-removebg-preview.png",
      description: "Varian malkist dengan taburan gula, cocok untuk camilan keluarga.",
      size: "245 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 157,
      name: "Kerupuk Kulit",
      price: 5000,
      category: "jajanan",
      stock: 10,
      image: "public/jajanan/KERUPUK_KULIT_5rb-removebg-preview.png",
      description: "Kerupuk dari kulit sapi/kerbau, gurih dan renyah, cocok untuk pendamping makan.",
      size: "10 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 158,
      name: "Kerupuk Pedas",
      price: 1000,
      category: "jajanan",
      stock: 25,
      image: "public/jajanan/KERUPUK_PEDAS-removebg-preview.png",
      description: "Kerupuk gurih pedas yang bikin ketagihan, cocok untuk pecinta rasa pedas.",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 159,
      name: "Makaroni Pedas",
      price: 1000,
      category: "jajanan",
      stock: 20,
      image: "public/jajanan/MAKARONI-removebg-preview.png",
      description: "Camilan makaroni kriuk dengan rasa pedas menggugah selera.",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 160,
      name: "Peanut Biskuit",
      price: 12000,
      category: "jajanan",
      stock: 7,
      image: "public/jajanan/PEANUT_BISCUIT-removebg-preview.png",
      description: "Biskuit renyah dengan Isian Selai Kacang yang gurih",
      size: "275 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 161,
      name: "Roma Kelapa",
      price: 2000,
      category: "jajanan",
      stock: 5,
      image: "public/jajanan/ROMA_KELAPA-removebg-preview.png",
      description: "Biskuit klasik dengan rasa kelapa, nikmat untuk segala suasana.",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 162,
      name: "Rose Cream Biskuit",
      price: 8000,
      category: "jajanan",
      stock: 3,
      image: "public/jajanan/ROSE_CREAM-removebg-preview.png",
      description: "Biskuit Sandwich dengan Isian Krim Pisang dan Vanila yang lembut dan renyah",
      size: "210 g",
      lastUpdated: new Date().toISOString(),
    },
  ],
  cart: [],
  isDarkMode: false,
};

function productReducer(state, action) {
  switch (action.type) {
    case "UPDATE_PRODUCT":
      return {
        ...state,
        products: state.products.map((product) =>
          product.id === action.payload.id
            ? {
                ...product,
                ...action.payload.updates,
                lastUpdated: new Date().toISOString(),
              }
            : product
        ),
      };
    case "DELETE_PRODUCT":
      return {
        ...state,
        products: state.products.filter(
          (product) => product.id !== action.payload
        ),
      };
    case "ADD_TO_CART":
      const existingItem = state.cart.find(
        (item) => item.id === action.payload.id
      );
      if (existingItem) {
        return {
          ...state,
          cart: state.cart.map((item) =>
            item.id === action.payload.id
              ? { ...item, quantity: item.quantity + 1 }
              : item
          ),
        };
      }
      return {
        ...state,
        cart: [...state.cart, { ...action.payload, quantity: 1 }],
      };
    case "REMOVE_FROM_CART":
      return {
        ...state,
        cart: state.cart.filter((item) => item.id !== action.payload),
      };
    case "UPDATE_CART_QUANTITY":
      if (action.payload.quantity === 0) {
        return {
          ...state,
          cart: state.cart.filter((item) => item.id !== action.payload.id),
        };
      }
      return {
        ...state,
        cart: state.cart.map((item) =>
          item.id === action.payload.id
            ? { ...item, quantity: action.payload.quantity }
            : item
        ),
      };
    case "CLEAR_CART":
      return {
        ...state,
        cart: [],
      };
    case "TOGGLE_DARK_MODE":
      return {
        ...state,
        isDarkMode: !state.isDarkMode,
      };
    default:
      return state;
  }
}

export function ProductProvider({ children }) {
  const [state, dispatch] = useReducer(productReducer, initialState);

  // Load cart from localStorage on mount
  useEffect(() => {
    const savedCart = localStorage.getItem("sembako-cart");
    if (savedCart) {
      const cartItems = JSON.parse(savedCart);
      cartItems.forEach((item) => {
        dispatch({ type: "ADD_TO_CART", payload: item });
      });
    }
  }, []);

  // Save cart to localStorage whenever cart changes
  useEffect(() => {
    localStorage.setItem("sembako-cart", JSON.stringify(state.cart));
  }, [state.cart]);

  const value = {
    ...state,
    dispatch,
    // Helper functions
    updateProduct: (id, updates) =>
      dispatch({ type: "UPDATE_PRODUCT", payload: { id, updates } }),
    deleteProduct: (id) => dispatch({ type: "DELETE_PRODUCT", payload: id }),
    addToCart: (product) => dispatch({ type: "ADD_TO_CART", payload: product }),
    removeFromCart: (id) => dispatch({ type: "REMOVE_FROM_CART", payload: id }),
    updateCartQuantity: (id, quantity) =>
      dispatch({ type: "UPDATE_CART_QUANTITY", payload: { id, quantity } }),
    clearCart: () => dispatch({ type: "CLEAR_CART" }),
    toggleDarkMode: () => dispatch({ type: "TOGGLE_DARK_MODE" }),
    // Computed values
    totalProducts: state.products.length,
    totalStock: state.products.reduce((sum, product) => sum + product.stock, 0),
    totalInventoryValue: state.products.reduce(
      (sum, product) => sum + product.price * product.stock,
      0
    ),
    lowStockProducts: state.products.filter((product) => product.stock < 10),
    cartTotal: state.cart.reduce(
      (sum, item) => sum + item.price * item.quantity,
      0
    ),
    cartItemsCount: state.cart.reduce((sum, item) => sum + item.quantity, 0),
  };

  return (
    <ProductContext.Provider value={value}>{children}</ProductContext.Provider>
  );
}

export function useProducts() {
  const context = useContext(ProductContext);
  if (!context) {
    throw new Error("useProducts must be used within a ProductProvider");
  }
  return context;
}
