"use client";

import { createContext, useContext, useReducer, useEffect } from "react";

const ProductContext = createContext();

const initialState = {
  products: [
    {
      id: 1,
      name: "Beras Sania Per 1kg",
      price: 17000,
      originalPrice: 17000,
      category: "bahan-makanan",
      stock: 3,
      image: "/foto bahan makanan/beras sania.png",
      description: "",
      size: "1 kg",
      isPromo: true,
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 2,
      name: "Bihun Jagung",
      price: 0,
      category: "bahan-makanan",
      stock: 8,
      image: "/foto bahan makanan/bihun jagung.png",
      description: "",
      size: "2 L",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 3,
      name: "Minyak Fortune",
      price: 10000,
      category: "bahan-makanan",
      stock: 12,
      image: "/foto bahan makanan/minyak fortune.png",
      description: "Minyak kualitas terbaik untuk memasak",
      size: "1/2 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 4,
      name: "Gandum Segitiga Biru",
      price: 10000,
      category: "bahan-makanan",
      stock: 15,
      image: "/foto bahan makanan/segitiga biru.png",
      description: "gandum berkualitas tinggi untuk berbagai olahan",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 5,
      name: "Minyak Cup Rosebrand",
      price: 5000,
      category: "bahan-makanan",
      stock: 20,
      image: "/foto bahan makanan/rose brand minyak cup.png",
      description: "MInyak dalam kemasan Cup",
      size: "220 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 6,
      name: "Minyak Kita",
      price: 18000,
      category: "bahan-makanan",
      stock: 25,
      image: "/foto bahan makanan/minyak_kita-removebg-preview.png",
      description: "Minyak goreng kita berkualitas",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 7,
      name: "Margarine Royal Palmia",
      price: 9000,
      category: "bahan-makanan",
      stock: 30,
      image: "/foto bahan makanan/palmia.png",
      description: "Margarine",
      size: "200g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 8,
      name: "Margarine Filma",
      price: 7000,
      category: "bahan-makanan",
      stock: 5,
      image:
        "/foto bahan makanan/d89a9ceae423d5212e022ec7b4017bd6-removebg-preview.png",
      description: "Margarine",
      size: "200g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 9,
      name: "Margarine For Vita",
      price: 7000,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/forvita.png",
      description: "Margarine",
      size: "200g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 10,
      name: "Sagu",
      price: 10000,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/sagu.png",
      description: "Sagu biasa",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 11,
      name: "Telur",
      price: 26000,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/telur.png",
      description: "Telur",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 12,
      name: "Tepung Beras",
      price: 7500,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/tepung beras.png",
      description: "Tepung Beras",
      size: "500 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 13,
      name: "Tepung Ketan",
      price: 11000,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/tepung ketan.png",
      description: "Tepung Ketan",
      size: "500 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 14,
      name: "Tepung Segitiga Biru",
      price: 12000,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/tepung segitiga biru.png",
      description: "Tepung",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 15,
      name: "Tepung Tapioka Cap Tani",
      price: 7500,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/tepung tapioka cap tani.png",
      description: "Tepung",
      size: "500 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 16,
      name: "Tepung Tapioka Cap Tani Liaw Liong",
      price: 33000,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/Tepung Tapioka Cap Tani Liaw Liong.png",
      description: "Tepung",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 17,
      name: "Tepung Terigu",
      price: 15000,
      category: "bahan-makanan",
      stock: 5,
      image: "/foto bahan makanan/tepung terigu.png",
      description: "Tepung",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 18,
      name: "Kecap Manis ABC",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/ABC_KECAP_MANIS_275ML.png",
      description: "",
      size: "275 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 19,
      name: "Agar Agar Powder",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/AGAR_AGAR.png",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 20,
      name: "Saos Extra Pedas Indofood",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/EXTRA_PEDAS_INDOFOOD_135ml.png",
      description: "",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 21,
      name: "Kecap Manis Indofood",
      price: 8000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/INDOFOOD_KECAP_BOTOL_135ML_8000-removebg-preview.png",
      description: "",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 22,
      name: "Kaldu Jamur Totole",
      price: 11000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/KALDU_JAMUR_TOTOLE_11000-removebg-preview.png",
      description: "",
      size: "80 gr",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 23,
      name: "Kecap Asin ABC",
      price: 6500,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/KECAP_ASIN_131ml_6500-removebg-preview.png",
      description: "",
      size: "131 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 24,
      name: "Kecap Asin Cap Bulan",
      price: 23000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/KECAP_ASIN_620ML_23rb-removebg-preview.png",
      description: "",
      size: "620 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 25,
      name: "Kecap Manis Bango",
      price: 1000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/KECAP_BANGO_1rb-removebg-preview.png",
      description: "",
      size: "25 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 26,
      name: "Kecap Manis Bango",
      price: 3000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/KECAP_BANGO_3rb-removebg-preview.png",
      description: "",
      size: "77 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 27,
      name: "Ketumbar Bubuk",
      price: 1000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/KETUMBAR_BUBUK_125gr-removebg-preview.png",
      description: "",
      size: "125 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 28,
      name: "Masako Ayam",
      price: 5000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/MASAKO_AYAM_123gr-removebg-preview.png",
      description: "",
      size: "123 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 29,
      name: "Masako Sapi",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/MASAKO_SAPI_123gr-removebg-preview.png",
      description: "",
      size: "250 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 30,
      name: "Masako Sapi Renceng",
      price: 500,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/MASAKO_SAPI_RENCENG-removebg-preview.png",
      description: "",
      size: "8 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 31,
      name: "Mayonaise Maestro",
      price: 28000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/MAYONAIS_MAESTRO_1kg_28rb-removebg-preview.png",
      description: "",
      size: "1 kg",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 32,
      name: "Masako Ayam Renceng",
      price: 500,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/MSAKO_AYAM_RENCENG-removebg-preview.png",
      description: "",
      size: "8 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 33,
      name: "Racik Bumbu Ayam Goreng",
      price: 2000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/RACIK_AYAM_GORENG-removebg-preview.png",
      description: "",
      size: "26 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 34,
      name: "Racik Bumbu Ayam Goreng Rempah",
      price: 2000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/RACIK_AYAM_GORENG_REMPAH-removebg-preview.png",
      description: "",
      size: "30 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 35,
      name: "Racik Bumbu Sayur Lodeh",
      price: 2000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/RACIK_SAYUR_LODEH-removebg-preview.png",
      description: "",
      size: "25 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 36,
      name: "Racik Bumbu Tempe & Tahu Goreng",
      price: 2000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/RACIK_TEMPE___TAHU_GORENG-removebg-preview.png",
      description: "",
      size: "20 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 37,
      name: "Sajiku Bumbu Sayur Asem",
      price: 2000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAJIKU_SAYUR_ASEM_30gr-removebg-preview.png",
      description: "",
      size: "30 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 38,
      name: "Saos Extra Hot DelMonte",
      price: 12000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAOS_EXTRA_HOT_DELMONTE_265ml_12000-removebg-preview.png",
      description: "",
      size: "265 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 39,
      name: "Sarden ABC",
      price: 28000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SARDEN_ABC_425gr_27_5rb___155gr___12rb-removebg-preview.png",
      description: "",
      size: "425 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 40,
      name: "Sarden ABC",
      price: 12000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SARDEN_ABC_425gr_27_5rb___155gr___12rb-removebg-preview.png",
      description: "",
      size: "155 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 41,
      name: "Sasa",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SASA_50gr-removebg-preview.png",
      description: "",
      size: "50 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 42,
      name: "Saos Sambal ABC",
      price: 8000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAUS_ABC_135ml_8000-removebg-preview.png",
      description: "",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 43,
      name: "Saus ABC Extreme Pedas",
      price: 16000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAUS_BOTOL_270ml_ABC_EXTREME_PEDAS_16000-removebg-preview.png",
      description: "",
      size: "270 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 44,
      name: "Saus Saset Delmonte /3pcs",
      price: 1000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAUS_SASET_DELMONTE_2_500-removebg-preview.png",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 45,
      name: "Saori Saus Tiram",
      price: 3000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAUS_TIRAM_SAORI-removebg-preview.png",
      description: "",
      size: "23 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 46,
      name: "Saus Tomat ABC",
      price: 8500,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAUS_TOMAT_135ml_8500-removebg-preview.png",
      description: "",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 47,
      name: "Saus Tomat ABC",
      price: 15000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SAUS_TOMAT_BOTOL_ABC_15000-removebg-preview.png",
      description: "",
      size: "275 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 48,
      name: "Susu Kental Manis Cap Enak",
      price: 12000,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/SKM_ENAAK_12rb-removebg-preview.png",
      description: "",
      size: "370 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 49,
      name: "Tepung Kobe Kentucky",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/TEPUNG_KOBE_KENTUCKY-removebg-preview.png",
      description: "",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 50,
      name: "Sajiku Tepung Serbaguna",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/TEPUNG_SAJIKU-removebg-preview.png",
      description: "",
      size: "40 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 51,
      name: "Terasi Udang",
      price: 0,
      category: "bumbu-masakan",
      stock: 5,
      image: "/Bumbu Masakan/TERASI-removebg-preview.png",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 52,
      name: "Kopi Bubuk Semendo",
      price: 18000,
      category: "minuman",
      stock: 5,
      image: "public/minuman/KOPI_BUBUK_18rb-removebg-preview.png",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 53,
      name: "Kopi Roda 666",
      price: 20000,
      originalPrice: 22000,
      category: "minuman",
      stock: 5,
      image: "public/minuman/KOPI_BUBUK_666_21_5rb-removebg-preview.png",
      description: "",
      size: "160 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 54,
      name: "Aqua Botol",
      price: 0,
      originalPrice: 0,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "1,5 l",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 55,
      name: "Chocodrink",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "28 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 56,
      name: "Chocolatos Coklat",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 57,
      name: "Chocolatos Matcha",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 58,
      name: "Energen Coklat",
      price: 2500,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "35 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 59,
      name: "Energen Kacang Hijau",
      price: 2500,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "32 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 60,
      name: "Energen Vanila",
      price: 2500,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "34 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 61,
      name: "Floridina",
      price: 3000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "350 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 62,
      name: "Aqua Galon",
      price: 0,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "19 l",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 63,
      name: "Vit Galon",
      price: 0,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "19 l",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 64,
      name: "Golda Coffee",
      price: 3500,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "200 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 65,
      name: "Good day Cappucino",
      price: 3000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "25 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 66,
      name: "Kopikap",
      price: 1000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "135 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 67,
      name: "Le Minerale",
      price: 0,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "600 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 68,
      name: "Aquali Cup",
      price: 1000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 69,
      name: "Mizone",
      price: 0,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "250 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 70,
      name: "Pop Ice Cappucino",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 71,
      name: "Pop Ice Choco Cream",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 72,
      name: "Pop Ice Permen Karet",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 73,
      name: "Pop Ice Strawberry",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 74,
      name: "Pop Ice Taro",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "23 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 75,
      name: "Power F",
      price: 1000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "180 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 76,
      name: "Kental Manis Frisian Flag Coklat",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "38 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 77,
      name: "Kental Manis Saset Frisian Flag",
      price: 2000,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "38 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 78,
      name: "Bonteh",
      price: 0,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "330 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 79,
      name: "Teh Pucuk Harum",
      price: 0,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "350 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 80,
      name: "Teh Celup Sariwangi",
      price: 1500,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "38 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 81,
      name: "TOP Coffee Gula Aren",
      price: 2500,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "22 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 82,
      name: "Torabika Moka",
      price: 2500,
      category: "minuman",
      stock: 5,
      image: "",
      description: "",
      size: "28 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 83,
      name: "Amplop 1pcs",
      price: 500,
      category: "nonfood",
      stock: 5,
      image: "public/NonFood/AMPLOP-removebg-preview (1).png",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 84,
      name: "Baterai ABC",
      price: 4000,
      category: "nonfood",
      stock: 5,
      image: "public/NonFood/BATERAII-removebg-preview (1).png",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 85,
      name: "Charm Safenight",
      price: 0,
      category: "nonfood",
      stock: 5,
      image: "public/NonFood/CHARM_SAFENIGHT_29cm-removebg-preview (1).png",
      description: "",
      size: "29 cm",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 86,
      name: "Charm ExtraMaxi Wing",
      price: 0,
      category: "nonfood",
      stock: 5,
      image: "",
      description:
        "public/NonFood/CHARM_SAFENIGHT_29cm-removebg-preview (1).png",
      size: "22 cm",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 87,
      name: "Pasta Gigi Ciptadent",
      price: 4000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "75 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 88,
      name: "Pasta Gigi Ciptadent",
      price: 7500,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "120 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 89,
      name: "Conditioner Saset Pantene",
      price: 0,
      category: "nonfood",
      stock: 5,
      image:
        "public/NonFood/CONDITIONER_SASET_PANTENE-removebg-preview (1).png",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 90,
      name: "Detergen Daia",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "47 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 91,
      name: "Downy ",
      price: 22000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "Pelembut & Pewangi Pakaian Konsentrat",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 92,
      name: "Gentle Gen",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/GENTLE_GEN-removebg-preview (1).png",
      description: "",
      size: "80 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 93,
      name: "Kapas Wajah Selection",
      price: 6000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 94,
      name: "Kapur Ajaib",
      price: 4000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/KAPUR_AJAIB_4rb-removebg-preview (1).png",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 95,
      name: "Kapur Barus",
      price: 0,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "35 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 96,
      name: "Kispray",
      price: 500,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/KISPRAY_-removebg-preview (1).png",
      description: "Pelicin, Pewangi & Pelembut Pakaian",
      size: "6 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 97,
      name: "Lampu Lanbo 10 Watt",
      price: 0,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/LAMPU_10w___15w-removebg-preview (1).png",
      description: "",
      size: "10 W",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 98,
      name: "Lampu Lanbo 15 Watt",
      price: 0,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/LAMPU_10w___15w-removebg-preview (1).png",
      description: "",
      size: "15 W",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 99,
      name: "Lem Kertas Glikol",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/LEM_KERTAS-removebg-preview (1).png",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 100,
      name: "Lem Korea",
      price: 0,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/LEM_SYAITONNIROJIM-removebg-preview (1).png",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 101,
      name: "Mama Lemon",
      price: 24000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "Sabun Pencuci Piring",
      size: "1,5 L",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 102,
      name: "Obat Nyamuk",
      price: 4000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "Obat Nyamuk Bakar",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 103,
      name: "Pena Standard Castello",
      price: 2000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/PENA-removebg-preview (1).png",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 104,
      name: "Pepsodent",
      price: 10000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "120 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 105,
      name: "Pepsodent",
      price: 14000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "190 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 106,
      name: "Downy Saset",
      price: 500,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfoof/PEWANGI_PAKAIAN_DOWNY-removebg-preview (1).png",
      description: "Pelembut & Pewangi Pakaian",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 107,
      name: "Downy Extra Saset",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image:
        "public/Nonfood/PEWANGI_PAKAIAN_DOWNY_1rb-removebg-preview (1).png",
      description: "Pelembut & Pewangi Pakaian",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 108,
      name: "Sabun Batang GIV",
      price: 3000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 109,
      name: "Sabun Batang Harmony",
      price: 3000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 110,
      name: "Sabun Batang Fres",
      price: 4000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 111,
      name: "Sabun Batang Lifebuoy",
      price: 4000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 112,
      name: "Sabun Batang Lux",
      price: 4500,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 113,
      name: "Sabun Cair Glow & Lovely",
      price: 5000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 114,
      name: "Sabun Cair Lifebuoy",
      price: 5000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 115,
      name: "Sabun Cair Shinzui",
      price: 5000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 116,
      name: "Sabun Colek Ekonomi",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 117,
      name: "Sabut Cuci Piring",
      price: 5000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 118,
      name: "Sabut Jaring",
      price: 5000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 119,
      name: "Sabut Stainless",
      price: 3000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 120,
      name: "Shampoo Saset Clear",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/SHAMPOO_SASET_CLEAR-removebg-preview (1).png",
      description: "Perawatan Komplit",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 121,
      name: "Shampoo Saset Clear Anti Ketombe & Rambut Rontok",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/SHAMPOO_SASET_CLEAR_OREN-removebg-preview (1).png",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 122,
      name: "Shampoo Saset Head & Shoulders",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image:
        "public/Nonfood/SHAMPOO_SASET_HEAD_SHOULDERS-removebg-preview (1).png",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 123,
      name: "Shampoo Saset Lifebuoy",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 124,
      name: "Shampoo Saset Pantene",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image:
        "public/Nonfood/SHAMPOO_SASET_PANTENE_AVOCADO-removebg-preview (1).png",
      description: "Pantene Avocado Fullness & Life",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 125,
      name: "Shampoo Saset Pantene Hijau",
      price: 0,
      category: "nonfood",
      stock: 5,
      image:
        "public/Nonfood/SHAMPOO_SASET_PANTENE_HIJAU-removebg-preview (1).png",
      description: "Perawatan Halus & Lembut",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 126,
      name: "Shampoo Saset Sunsilk",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/SHAMPOO_SASET_SUNSILK-removebg-preview (1).png",
      description: "Shampoo Saset Sunsilk Anti Ketombe",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 127,
      name: "Sikat Ggi Formula",
      price: 4000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 128,
      name: "Soklin Jumbo",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/SO_KLIN_JUMBO-removebg-preview (1).png",
      description: "Soklin Liquid Power Clean Action",
      size: "40 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 129,
      name: "Soffell",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "public/Nonfood/SOFELL_JERUK-removebg-preview (1).png",
      description: "Lotion Anti Nyamuk",
      size: "5 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 130,
      name: "Soklin Lantai",
      price: 1000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "52 ml",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 131,
      name: "Tali Rapia",
      price: 2000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 132,
      name: "Tissue Jolly",
      price: 10000,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "250 Sheets",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 133,
      name: "Lem Korea",
      price: 0,
      category: "nonfood",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 134,
      name: "Bihun",
      price: 0,
      category: "mie",
      stock: 5,
      image: "",
      description: "",
      size: "100 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 135,
      name: "Indomie Ayam Bawang",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Kuah Rasa Ayam Bawang",
      size: "69 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 136,
      name: "Indomie Ayam Geprek",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Goreng Rasa Ayam Geprek",
      size: "85 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 137,
      name: "Indomie Goreng",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Goreng Original",
      size: "80 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 138,
      name: "Indomie Aceh",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Goreng Aceh Khas Aceh",
      size: "90 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 139,
      name: "Indomie Goreng Jumbo",
      price: 4500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Goreng Original Porsi Jumbo",
      size: "129 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 140,
      name: "Indomie Kuah Kari Ayam",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Kuah Rasa Kari Ayam",
      size: "72 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 141,
      name: "Indomie Kuah Soto Mie",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Kuah Rasa Soto Mie",
      size: "70 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 142,
      name: "Indomie Mi Celor",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Kuah Rasa Mi Celor Khas Palembang",
      size: "75 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 143,
      name: "Indomie Rendang",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Goreng Rasa Rendang Khas Sumatera Barat",
      size: "91 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 144,
      name: "Mie Gaga 100",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Goreng Extra Pedas",
      size: "85 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 145,
      name: "Mie Sedaap Soto",
      price: 3500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Kuah Rasa Soto Extra Koya Gurih",
      size: "76 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 146,
      name: "Mie Telor A1",
      price: 0,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Telor Gaga A1",
      size: "180 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 147,
      name: "Pop Mie Baso",
      price: 5000,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Instan Cup Pop Mie Rasa Baso",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 148,
      name: "Sarimie Isi 2 Ayam Kecap",
      price: 4500,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Goreng Rasa Ayam Kecap",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 149,
      name: "Sohun",
      price: 0,
      category: "mie",
      stock: 5,
      image: "",
      description: "Sohun Kering Cap Stier",
      size: "50 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 150,
      name: "Supermie Sup Sayuran",
      price: 2000,
      category: "mie",
      stock: 5,
      image: "",
      description: "Mie Kuah Rasa Sup Sayuran",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 151,
      name: "Bakpia",
      price: 2000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "Bakpia Rasa Keju & Kacang Hijau",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 152,
      name: "Chocolatos",
      price: 1000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "Rasa Coklat & Keju",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 153,
      name: "Biskuit Coco Puff",
      price: 0,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "",
      size: "0 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 154,
      name: "Crispy Crackers",
      price: 12000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "",
      size: "250 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 155,
      name: "Hatari Malkist",
      price: 0,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "",
      size: "245 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 156,
      name: "Hatari Malkist Margarine",
      price: 0,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "",
      size: "245 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 157,
      name: "Kerupuk Kulit",
      price: 5000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 158,
      name: "Kerupuk Pedas",
      price: 1000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 159,
      name: "Makaroni Pedas",
      price: 1000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 160,
      name: "Peanut Biskuit",
      price: 0,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "Biskuit dengan Isian Selai Kacang",
      size: "275 g",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 161,
      name: "Roma Kelapa",
      price: 2000,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "Roma Kelapa Cokelat",
      size: "",
      lastUpdated: new Date().toISOString(),
    },
    {
      id: 162,
      name: "Rose Cream Biskuit",
      price: 0,
      category: "jajanan",
      stock: 5,
      image: "",
      description: "Biskuit Sandwich dengan Isian Krim Pisang dan Vanila",
      size: "210 g",
      lastUpdated: new Date().toISOString(),
    },
  ],
  cart: [],
  isDarkMode: false,
};

function productReducer(state, action) {
  switch (action.type) {
    case "UPDATE_PRODUCT":
      return {
        ...state,
        products: state.products.map((product) =>
          product.id === action.payload.id
            ? {
                ...product,
                ...action.payload.updates,
                lastUpdated: new Date().toISOString(),
              }
            : product
        ),
      };
    case "DELETE_PRODUCT":
      return {
        ...state,
        products: state.products.filter(
          (product) => product.id !== action.payload
        ),
      };
    case "ADD_TO_CART":
      const existingItem = state.cart.find(
        (item) => item.id === action.payload.id
      );
      if (existingItem) {
        return {
          ...state,
          cart: state.cart.map((item) =>
            item.id === action.payload.id
              ? { ...item, quantity: item.quantity + 1 }
              : item
          ),
        };
      }
      return {
        ...state,
        cart: [...state.cart, { ...action.payload, quantity: 1 }],
      };
    case "REMOVE_FROM_CART":
      return {
        ...state,
        cart: state.cart.filter((item) => item.id !== action.payload),
      };
    case "UPDATE_CART_QUANTITY":
      if (action.payload.quantity === 0) {
        return {
          ...state,
          cart: state.cart.filter((item) => item.id !== action.payload.id),
        };
      }
      return {
        ...state,
        cart: state.cart.map((item) =>
          item.id === action.payload.id
            ? { ...item, quantity: action.payload.quantity }
            : item
        ),
      };
    case "CLEAR_CART":
      return {
        ...state,
        cart: [],
      };
    case "TOGGLE_DARK_MODE":
      return {
        ...state,
        isDarkMode: !state.isDarkMode,
      };
    default:
      return state;
  }
}

export function ProductProvider({ children }) {
  const [state, dispatch] = useReducer(productReducer, initialState);

  // Load cart from localStorage on mount
  useEffect(() => {
    const savedCart = localStorage.getItem("sembako-cart");
    if (savedCart) {
      const cartItems = JSON.parse(savedCart);
      cartItems.forEach((item) => {
        dispatch({ type: "ADD_TO_CART", payload: item });
      });
    }
  }, []);

  // Save cart to localStorage whenever cart changes
  useEffect(() => {
    localStorage.setItem("sembako-cart", JSON.stringify(state.cart));
  }, [state.cart]);

  const value = {
    ...state,
    dispatch,
    // Helper functions
    updateProduct: (id, updates) =>
      dispatch({ type: "UPDATE_PRODUCT", payload: { id, updates } }),
    deleteProduct: (id) => dispatch({ type: "DELETE_PRODUCT", payload: id }),
    addToCart: (product) => dispatch({ type: "ADD_TO_CART", payload: product }),
    removeFromCart: (id) => dispatch({ type: "REMOVE_FROM_CART", payload: id }),
    updateCartQuantity: (id, quantity) =>
      dispatch({ type: "UPDATE_CART_QUANTITY", payload: { id, quantity } }),
    clearCart: () => dispatch({ type: "CLEAR_CART" }),
    toggleDarkMode: () => dispatch({ type: "TOGGLE_DARK_MODE" }),
    // Computed values
    totalProducts: state.products.length,
    totalStock: state.products.reduce((sum, product) => sum + product.stock, 0),
    totalInventoryValue: state.products.reduce(
      (sum, product) => sum + product.price * product.stock,
      0
    ),
    lowStockProducts: state.products.filter((product) => product.stock < 10),
    cartTotal: state.cart.reduce(
      (sum, item) => sum + item.price * item.quantity,
      0
    ),
    cartItemsCount: state.cart.reduce((sum, item) => sum + item.quantity, 0),
  };

  return (
    <ProductContext.Provider value={value}>{children}</ProductContext.Provider>
  );
}

export function useProducts() {
  const context = useContext(ProductContext);
  if (!context) {
    throw new Error("useProducts must be used within a ProductProvider");
  }
  return context;
}
